// Initial APP
export const LOAD_INITIAL_CONFIG = 'LOAD_INITIAL_CONFIG';
export const LOAD_INITIAL_CONFIG_FAILED = 'LOAD_INITIAL_CONFIG_FAILED';

export const LOAD_HEADER = 'LOAD_HEADER';
export const LOAD_HEADER_FAILED = 'LOAD_HEADER_FAILED';

export const LOAD_FOOTER = 'LOAD_FOOTER';
export const LOAD_FOOTER_FAILED = 'LOAD_FOOTER_FAILED';
